import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import"../../node_modules/@fortawesome/fontawesome-free/css/all.min.css"
import "./globals.css";
import Navbar from "./_components/navbar/navbar";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import MySessionProvider from "./_providers/MySessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >



<MySessionProvider  >

  {/* Start Navbar */}
  <Navbar/>
  {/* End Navbar */}
    
        {children}


      <Toaster/>


</MySessionProvider>









      </body>
    </html>
  );
}
